name: fbfmaproom2
channels:
  - conda-forge
  - defaults
dependencies:

    # rasterio build fails with python 3.10
    # https://github.com/rasterio/rasterio/issues/2333
  - python=3.9
  - cftime

  # some later version removes the __wrapped__ attribute on callbacks,
  # which is used by some tests
  - dash=2.3.1

  - dash-leaflet
  - dash-bootstrap-components
  - numpy
  - opencv

    # Newer versions of Pandas emit warnings when passed a psycopg2
    # connection. To upgrade, use psycopg2 via SLQAlchemy.
  - pandas=1.3
  - pip  # to support compilation of mod_wsgi from source
  - psycopg2
  - pyyaml
  - rasterio
  - shapely

  - werkzeug<2.1 # werkzeug 2.1 spews warnings at dev server startup

  - xarray
  - zarr
