name: dash
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - aiobotocore=1.2.0
  - aiohttp=3.7.3
  - aioitertools=0.7.1
  - appdirs=1.4.4
  - asciitree=0.3.3
  - async-timeout=3.0.1
  - attrs=20.3.0
  - bjoern=3.0.1
  - black=20.8b1
  - bokeh=2.2.3
  - boost-cpp=1.74.0
  - botocore=1.19.52
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - cartopy=0.18.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - cfgrib=0.9.8.5
  - cfitsio=3.470
  - cftime=1.3.0
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cloudpickle=1.6.0
  - cryptography=3.2.1
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dash=1.17.0
  - dash-core-components=1.13.0
  - dash-daq=0.5.0
  - dash-html-components=1.1.1
  - dash-renderer=1.8.3
  - dash-table=4.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - dataclasses=0.7
  - distributed=2.30.1
  - eccodes=2.20.0
  - expat=2.2.9
  - fasteners=0.14.1
  - ffmpeg=4.3.1
  - flask=1.1.2
  - flask-compress=1.8.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.5
  - fsspec=0.8.5
  - future=0.18.2
  - gdal=3.1.4
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.3
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - graphviz=2.42.3
  - harfbuzz=2.7.2
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=67.1
  - idna=2.10
  - itsdangerous=1.1.0
  - jasper=1.900.1
  - jinja2=2.11.2
  - jmespath=0.10.0
  - jpeg=9d
  - json-c=0.13.1
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lame=3.100
  - lcms2=2.11
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libcxx=11.0.0
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgdal=3.1.4
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.66.3
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libopencv=4.5.0
  - libpng=1.6.37
  - libpq=12.3
  - libspatialite=5.0.0
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-openmp=11.0.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - monotonic=1.5
  - msgpack-python=1.0.0
  - multidict=5.1.0
  - mypy=0.790
  - mypy_extensions=0.4.3
  - nc-time-axis=1.2.0
  - ncurses=6.2
  - netcdf4=1.5.5
  - nettle=3.6
  - numcodecs=0.7.3
  - numpy=1.19.4
  - olefile=0.46
  - opencv=4.5.0
  - openh264=2.1.1
  - openjpeg=2.3.1
  - openssl=1.1.1j
  - packaging=20.7
  - pandas=1.1.5
  - partd=1.1.0
  - pathspec=0.8.1
  - pcre=8.44
  - pillow=8.0.1
  - pip=20.3.1
  - pixman=0.40.0
  - plotly=4.14.0
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - proj=7.1.1
  - psutil=5.7.3
  - psycopg2=2.8.6
  - py-opencv=4.5.0
  - pycairo=1.20.0
  - pycparser=2.20
  - pydot=1.4.1
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pyshp=2.1.2
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil=2.8.1
  - python-graphviz=0.16
  - python_abi=3.9
  - pytz=2020.4
  - pyyaml=5.3.1
  - rasterio=1.1.8
  - readline=8.0
  - regex=2020.11.13
  - requests=2.24.0
  - retrying=1.3.3
  - s3fs=0.5.2
  - scipy=1.5.3
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - snuggs=1.4.7
  - sortedcontainers=2.3.0
  - sqlite=3.34.0
  - tblib=1.6.0
  - tiledb=2.1.3
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - typed-ast=1.4.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzcode=2020a
  - tzdata=2020d
  - urllib3=1.25.11
  - werkzeug=1.0.1
  - wheel=0.36.1
  - wrapt=1.12.1
  - x264=1!152.20180806
  - xarray=0.16.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zarr=2.6.1
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - dash-leaflet==0.1.13
    - docutils==0.16
    - geobuf==1.1.1
    - protobuf==3.13.0
    - pyaconf==0.7.1
    - queuepool==1.3.1
    - rstcheck==3.3.1
