name: flex_fcst_adm
channels:
  - conda-forge
  - defaults
  - iri-nextgen
dependencies:
  - python=3.9
  - cptio
  - dash
  - dash-leaflet
  - dash-bootstrap-components
  - dask
  - numpy
  - opencv
  - pandas=1.3
  - psycopg2
  - rasterio
  - scipy
  - shapely
  - werkzeug<2.1 # 2.1 spews warnings at dev server start
  - xarray
  - yaml
  - zarr
  - bottleneck
