# App set up
mode: debug  # debug, devel or prod
dev_server_interface: 127.0.0.1
dev_server_port: 8050
dev_processes: 4
loglevel: info

db:
    dbname: iridb
    host: dlcomputemon1.iri.columbia.edu
    port: 5432
    user: ingrid  # user name
    password: SNIP
