name: enactsmaproom
channels:
  - conda-forge
  - defaults
dependencies:
  - dash
  - dash-daq
  - flask
  - numpy
  - pandas
  - psycopg2
  - shapely
  - xarray
  - yaml
  - zarr
  - netcdf4
  - dask
  - mercantile
  - pillow
  - dash-leaflet
  - dash-bootstrap-components==0.13
  - dash-extensions
  - pip
  - pip:
    - pyaconf
    - queuepool
    - dash-html-components
    - dash-core-components
    - dash-table
