name: enactsmaproom
channels:
  - conda-forge
  - defaults
dependencies:
  - dash
  - dash-daq
  - flask
  - numpy
  - pandas
  - psycopg2
  - rasterio
  - shapely
  - xarray
  - yaml
  - zarr
  - netcdf4
  - dask
  - mercantile
  - pillow
  - pip
  - pip:
    - dash-leaflet
    - pyaconf
    - queuepool
    - dash-bootstrap-components
    - dash-extensions
